name: Streamlit App Tests

on:
  push:
    branches: ["main", "refactor"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt')"
      
      - name: Run tests
        run: |
          pytest tests/ -v