name: Streamlit App Tests

on:
  push:
    branches: ["main", "refactor"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for faster checkout
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-xdist
      
      - name: Cache NLTK data
        uses: actions/cache@v3
        with:
          path: ~/nltk_data
          key: nltk-data-${{ runner.os }}
      
      - name: Download NLTK data
        run: |
          python -c "import nltk; nltk.download('punkt')"
      
      - name: Run specific tests
        run: |
          pytest tests/test_app.py tests/test_metrics.py -v